// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyCKSVJLrJJX8GByAMBfE8ePaisr10HAixY',
  appId: '1:766151640143:android:9634e6dd7b9f7590e4163a',
  messagingSenderId: '766151640143',
  projectId: 'nutrion-597b9',
  storageBucket: 'nutrion-597b9.firebasestorage.app',
);

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyARWcnO-t9VfqEWZaFrO1pxW4PV9teiArY',
  //   appId: '1:872837599947:android:42852b91f9f32b6fd4014e',
  //   messagingSenderId: '872837599947',
  //   projectId: 'nutriscan-569a2',
  //   storageBucket: 'nutriscan-569a2.firebasestorage.app',
  // );

  static const FirebaseOptions ios = FirebaseOptions(
   apiKey: 'AIzaSyCKSVJLrJJX8GByAMBfE8ePaisr10HAixY',
  appId: '1:766151640143:android:9634e6dd7b9f7590e4163a',
  messagingSenderId: '766151640143',
  projectId: 'nutrion-597b9',
  storageBucket: 'nutrion-597b9.firebasestorage.app',
  );
}
